spring:
  application:
    name: User_Service

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  datasource:
    url: jdbc:mysql://localhost:3306/event_management_db?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: 1234
    driverClassName: com.mysql.cj.jdbc.Driver


  jpa:
    # database-platform එක Hibernate 7 වලදී අවශ්‍ය නැහැ,
    # ඒ වෙනුවට මේ line එක විතරක් පාවිච්චි කරන්න:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect